export const WeatherIcons = {
  "01d": "/icons/status/sunny.svg",
  "01n": "/icons/status/night.svg",
  "02d": "/icons/status/day.svg",
  "02n": "/icons/status/cloudy-night.svg",
  "03d": "/icons/status/cloudy.svg",
  "03n": "/icons/status/cloudy.svg",
  "04d": "/icons/status/perfect-day.svg",
  "04n": "/icons/status/cloudy-night.svg",
  "09d": "/icons/status/rain.svg",
  "09n": "/icons/status/rain-night.svg",
  "10d": "/icons/status/rain.svg",
  "10n": "/icons/status/rain-night.svg",
  "11d": "/icons/status/storm.svg",
  "11n": "/icons/status/storm.svg",
};